from __future__ import (print_function, division, unicode_literals, absolute_import)


class KmipError(Exception):
    """
    A KMIP error as specified in the spec.
    
    Args:
        result_status (enums.ResultStatus): the result status.
        result_reason (enums.ResultReason): the error reason.
        result_message (str): the error message generated by the server.
    """
    def __init__(self, result_status, result_reason, result_message):
        self.result_status = result_status
        self.result_reason = result_reason
        self.result_message = result_message
        desc = 'KMIP error; status = {}, reason = {}, message = {}'.format(
            self.result_status, self.result_reason, self.result_message)
        super(KmipError, self).__init__(self, desc)
