from __future__ import (print_function, division, unicode_literals, absolute_import)
from kkmip import enums


TAG_TYPE_MAP = {
    enums.Tag.ActivationDate: [enums.ItemType.DateTime],
    enums.Tag.Active: [enums.ItemType.Boolean],
    enums.Tag.AlternativeName: [enums.ItemType.Structure],
    enums.Tag.AlternativeNameType: [enums.ItemType.Enumeration],
    enums.Tag.AlternativeNameValue: [enums.ItemType.TextString],
    enums.Tag.AlwaysSensitive: [enums.ItemType.Boolean],
    enums.Tag.ApplicationArgument: [enums.ItemType.TextString],
    enums.Tag.ApplicationBasicInfo: [enums.ItemType.Structure],
    enums.Tag.ApplicationData: [enums.ItemType.TextString],
    enums.Tag.ApplicationEntryPoint: [enums.ItemType.TextString],
    enums.Tag.ApplicationInstanceInfo: [enums.ItemType.Structure],
    enums.Tag.ApplicationName: [enums.ItemType.TextString],
    enums.Tag.ApplicationNamespace: [enums.ItemType.TextString],
    enums.Tag.ApplicationPort: [enums.ItemType.Structure],
    enums.Tag.ApplicationRunning: [enums.ItemType.Boolean],
    enums.Tag.ApplicationSpecificInformation: [enums.ItemType.Structure],
    enums.Tag.ArchiveDate: [enums.ItemType.DateTime],
    enums.Tag.AsynchronousCapability: [enums.ItemType.Boolean],
    enums.Tag.AsynchronousCorrelationValue: [enums.ItemType.ByteString],
    enums.Tag.AsynchronousIndicator: [enums.ItemType.Boolean],
    enums.Tag.AttestationAssertion: [enums.ItemType.ByteString],
    enums.Tag.AttestationCapability: [enums.ItemType.Boolean],
    enums.Tag.AttestationCapableIndicator: [enums.ItemType.Boolean],
    enums.Tag.AttestationMeasurement: [enums.ItemType.ByteString],
    enums.Tag.AttestationType: [enums.ItemType.Enumeration],
    enums.Tag.Attribute: [enums.ItemType.Structure],
    enums.Tag.AttributeIndex: [enums.ItemType.Integer],
    enums.Tag.AttributeName: [enums.ItemType.TextString],
    enums.Tag.AuthenticatedEncryptionAdditionalData: [enums.ItemType.ByteString],
    enums.Tag.AuthenticatedEncryptionTag: [enums.ItemType.ByteString],
    enums.Tag.Authentication: [enums.ItemType.Structure],
    enums.Tag.BatchContinueCapability: [enums.ItemType.Boolean],
    enums.Tag.BatchCount: [enums.ItemType.Integer],
    enums.Tag.BatchErrorContinuationOption: [enums.ItemType.Enumeration],
    enums.Tag.BatchItem: [enums.ItemType.Structure],
    enums.Tag.BatchOrderOption: [enums.ItemType.Boolean],
    enums.Tag.BatchUndoCapability: [enums.ItemType.Boolean],
    enums.Tag.BatteryVoltage: [enums.ItemType.Integer],
    enums.Tag.BlockCipherMode: [enums.ItemType.Enumeration],
    enums.Tag.CACertificate: [enums.ItemType.ByteString],
    enums.Tag.CPU: [enums.ItemType.Integer],
    enums.Tag.CRTCoefficient: [enums.ItemType.BigInteger],
    enums.Tag.CancellationResult: [enums.ItemType.Enumeration],
    enums.Tag.CapabilityInformation: [enums.ItemType.Structure],
    enums.Tag.Certificate: [enums.ItemType.Structure],
    enums.Tag.CertificateIdentifier: [enums.ItemType.Structure],
    enums.Tag.CertificateIssuer: [enums.ItemType.Structure],
    enums.Tag.CertificateIssuerAlternativeName: [enums.ItemType.TextString],
    enums.Tag.CertificateIssuerDistinguishedName: [enums.ItemType.TextString],
    enums.Tag.CertificateLength: [enums.ItemType.Integer],
    enums.Tag.CertificateRequest: [enums.ItemType.ByteString],
    enums.Tag.CertificateRequestType: [enums.ItemType.Enumeration],
    enums.Tag.CertificateSerialNumber: [enums.ItemType.ByteString],
    enums.Tag.CertificateSubject: [enums.ItemType.Structure],
    enums.Tag.CertificateSubjectAlternativeName: [enums.ItemType.TextString],
    enums.Tag.CertificateSubjectDistinguishedName: [enums.ItemType.TextString],
    enums.Tag.CertificateType: [enums.ItemType.Enumeration],
    enums.Tag.CertificateValue: [enums.ItemType.ByteString],
    enums.Tag.ClearHomeDirectory: [enums.ItemType.Boolean],
    enums.Tag.ClearTmpDirectory: [enums.ItemType.Boolean],
    enums.Tag.ClearVarDirectory: [enums.ItemType.Boolean],
    enums.Tag.ClientCorrelationValue: [enums.ItemType.TextString],
    enums.Tag.ClientRegistrationMethod: [enums.ItemType.Enumeration],
    enums.Tag.CommonTemplateAttribute: [enums.ItemType.Structure],
    enums.Tag.CompromiseDate: [enums.ItemType.DateTime],
    enums.Tag.CompromiseOccurrenceDate: [enums.ItemType.DateTime],
    enums.Tag.ContactInformation: [enums.ItemType.TextString],
    enums.Tag.CorrelationValue: [enums.ItemType.ByteString],
    enums.Tag.CounterLength: [enums.ItemType.Integer],
    enums.Tag.Credential: [enums.ItemType.Structure],
    enums.Tag.CredentialType: [enums.ItemType.Enumeration],
    enums.Tag.CredentialValue: [enums.ItemType.Structure],
    enums.Tag.CriticalityIndicator: [enums.ItemType.Boolean],
    enums.Tag.CryptographicAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.CryptographicDomainParameters: [enums.ItemType.Structure],
    enums.Tag.CryptographicLength: [enums.ItemType.Integer],
    enums.Tag.CryptographicParameters: [enums.ItemType.Structure],
    enums.Tag.CryptographicUsageMask: [enums.ItemType.Integer],
    enums.Tag.D: [enums.ItemType.BigInteger],
    enums.Tag.DRBGAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.Data: [enums.ItemType.ByteString],
    enums.Tag.DataLength: [enums.ItemType.Integer],
    enums.Tag.DataPath: [enums.ItemType.Structure],
    enums.Tag.Day: [enums.ItemType.TextString],
    enums.Tag.DeactivationDate: [enums.ItemType.DateTime],
    enums.Tag.DerivationData: [enums.ItemType.ByteString],
    enums.Tag.DerivationMethod: [enums.ItemType.Enumeration],
    enums.Tag.DerivationParameters: [enums.ItemType.Structure],
    enums.Tag.DestroyAction: [enums.ItemType.Enumeration],
    enums.Tag.DestroyDate: [enums.ItemType.DateTime],
    enums.Tag.DeviceIdentifier: [enums.ItemType.TextString],
    enums.Tag.DeviceSerialNumber: [enums.ItemType.TextString],
    enums.Tag.DeviceStatus: [enums.ItemType.Structure],
    enums.Tag.Digest: [enums.ItemType.Structure],
    enums.Tag.DigestValue: [enums.ItemType.ByteString],
    enums.Tag.DigitalSignatureAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.Disk: [enums.ItemType.Integer],
    enums.Tag.EncodingOption: [enums.ItemType.Enumeration],
    enums.Tag.EncryptionKeyInformation: [enums.ItemType.Structure],
    enums.Tag.ExtensionInformation: [enums.ItemType.Structure],
    enums.Tag.ExtensionName: [enums.ItemType.TextString],
    enums.Tag.ExtensionTag: [enums.ItemType.Integer],
    enums.Tag.ExtensionType: [enums.ItemType.Integer],
    enums.Tag.ExternalPort: [enums.ItemType.Integer],
    enums.Tag.Extractable: [enums.ItemType.Boolean],
    enums.Tag.FIPS186Variation: [enums.ItemType.Enumeration],
    enums.Tag.FIPSActiveMode: [enums.ItemType.Boolean],
    enums.Tag.FileData: [enums.ItemType.ByteString],
    enums.Tag.FileDataDigest: [enums.ItemType.ByteString],
    enums.Tag.FileType: [enums.ItemType.Enumeration],
    enums.Tag.FinalIndicator: [enums.ItemType.Boolean],
    enums.Tag.FixedFieldLength: [enums.ItemType.Integer],
    enums.Tag.Fresh: [enums.ItemType.Boolean],
    enums.Tag.FunctionName: [enums.ItemType.TextString],
    enums.Tag.G: [enums.ItemType.BigInteger],
    enums.Tag.HTTPSPort: [enums.ItemType.Integer],
    enums.Tag.HashingAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.Hour: [enums.ItemType.TextString],
    enums.Tag.IVCounterNonce: [enums.ItemType.ByteString],
    enums.Tag.IVLength: [enums.ItemType.Integer],
    enums.Tag.ImageData: [enums.ItemType.ByteString],
    enums.Tag.InitIndicator: [enums.ItemType.Boolean],
    enums.Tag.InitialCounterValue: [enums.ItemType.Integer],
    enums.Tag.InitialDate: [enums.ItemType.DateTime],
    enums.Tag.InitializationVector: [enums.ItemType.ByteString],
    enums.Tag.InstanceIdentifier: [enums.ItemType.TextString],
    enums.Tag.InternalPort: [enums.ItemType.Integer],
    enums.Tag.IntrusionState: [enums.ItemType.Enumeration],
    enums.Tag.InvocationFieldLength: [enums.ItemType.Integer],
    enums.Tag.Issuer: [enums.ItemType.TextString],
    enums.Tag.IssuerAlternativeName: [enums.ItemType.ByteString],
    enums.Tag.IssuerDistinguishedName: [enums.ItemType.ByteString],
    enums.Tag.IterationCount: [enums.ItemType.Integer],
    enums.Tag.J: [enums.ItemType.BigInteger],
    enums.Tag.KNETState: [enums.ItemType.Enumeration],
    enums.Tag.Key: [enums.ItemType.ByteString],
    enums.Tag.KeyBlock: [enums.ItemType.Structure],
    enums.Tag.KeyCompressionType: [enums.ItemType.Enumeration],
    enums.Tag.KeyFormatType: [enums.ItemType.Enumeration],
    enums.Tag.KeyMaterial: [enums.ItemType.ByteString, enums.ItemType.Structure],
    enums.Tag.KeyPartIdentifier: [enums.ItemType.Integer],
    enums.Tag.KeyRoleType: [enums.ItemType.Enumeration],
    enums.Tag.KeyValue: [enums.ItemType.ByteString, enums.ItemType.Structure],
    enums.Tag.KeyValueLocation: [enums.ItemType.Structure],
    enums.Tag.KeyValueLocationType: [enums.ItemType.Enumeration],
    enums.Tag.KeyValueLocationValue: [enums.ItemType.TextString],
    enums.Tag.KeyValuePresent: [enums.ItemType.Boolean],
    enums.Tag.KeyWrapType: [enums.ItemType.Enumeration],
    enums.Tag.KeyWrappingData: [enums.ItemType.Structure],
    enums.Tag.KeyWrappingSpecification: [enums.ItemType.Structure],
    enums.Tag.KnetAllocatedBytes: [enums.ItemType.Integer],
    enums.Tag.KnetAuthErrorCount: [enums.ItemType.Integer],
    enums.Tag.KnetAvailableBytes: [enums.ItemType.Integer],
    enums.Tag.KnetBusyTime: [enums.ItemType.Integer],
    enums.Tag.KnetClientsConnected: [enums.ItemType.Integer],
    enums.Tag.KnetCommandCount: [enums.ItemType.Integer],
    enums.Tag.KnetErrorCount: [enums.ItemType.Integer],
    enums.Tag.KnetFIPSModeEnabled: [enums.ItemType.Boolean],
    enums.Tag.KnetFirmwareVersion: [enums.ItemType.TextString],
    enums.Tag.KnetHardwareVersion: [enums.ItemType.TextString],
    enums.Tag.KnetIPInt1: [enums.ItemType.TextString],
    enums.Tag.KnetIPInt2: [enums.ItemType.TextString],
    enums.Tag.KnetLicenseID: [enums.ItemType.TextString],
    enums.Tag.KnetMCT7ModeEnabled: [enums.ItemType.Boolean],
    enums.Tag.KnetModel: [enums.ItemType.TextString],
    enums.Tag.KnetNetwork1Bandwidth: [enums.ItemType.Integer],
    enums.Tag.KnetNetwork1Status: [enums.ItemType.TextString],
    enums.Tag.KnetNetwork2Bandwidth: [enums.ItemType.Integer],
    enums.Tag.KnetNetwork2Status: [enums.ItemType.TextString],
    enums.Tag.KnetNumberOfObjects: [enums.ItemType.Integer],
    enums.Tag.KnetNumberOfUsers: [enums.ItemType.Integer],
    enums.Tag.KnetPCIModeEnabled: [enums.ItemType.Boolean],
    enums.Tag.KnetPerfomanceLimit: [enums.ItemType.Integer],
    enums.Tag.KnetProcessorUsage: [enums.ItemType.Integer],
    enums.Tag.KnetSecureExecutionEnabled: [enums.ItemType.Boolean],
    enums.Tag.KnetSelfTestResult: [enums.ItemType.TextString],
    enums.Tag.KnetSelfTestTime: [enums.ItemType.DateTime],
    enums.Tag.KnetSerialNumber: [enums.ItemType.TextString],
    enums.Tag.KnetTemperature: [enums.ItemType.Integer],
    enums.Tag.KnetTotalBytes: [enums.ItemType.Integer],
    enums.Tag.KnetVHSMsAvailable: [enums.ItemType.Integer],
    enums.Tag.KnetVHSMsCreated: [enums.ItemType.Integer],
    enums.Tag.KnetVhsmEnabled: [enums.ItemType.Boolean],
    enums.Tag.KnetVhsmLimit: [enums.ItemType.Integer],
    enums.Tag.LanDNS: [enums.ItemType.TextString],
    enums.Tag.LanGateway: [enums.ItemType.TextString],
    enums.Tag.LanIP: [enums.ItemType.TextString],
    enums.Tag.LanInterface: [enums.ItemType.Enumeration],
    enums.Tag.LanInterfaceInformation: [enums.ItemType.Structure],
    enums.Tag.LanMask: [enums.ItemType.TextString],
    enums.Tag.LastChangeDate: [enums.ItemType.DateTime],
    enums.Tag.LeaseTime: [enums.ItemType.Interval],
    enums.Tag.Link: [enums.ItemType.Structure],
    enums.Tag.LinkType: [enums.ItemType.Enumeration],
    enums.Tag.LinkedObjectIdentifier: [enums.ItemType.TextString],
    enums.Tag.LocatedItems: [enums.ItemType.Integer],
    enums.Tag.LogLevel: [enums.ItemType.Enumeration],
    enums.Tag.MACData: [enums.ItemType.ByteString],
    enums.Tag.MACSignature: [enums.ItemType.ByteString],
    enums.Tag.MACSignatureKeyInformation: [enums.ItemType.TextString, enums.ItemType.Structure],
    enums.Tag.MachineIdentifier: [enums.ItemType.TextString],
    enums.Tag.Major: [enums.ItemType.Integer],
    enums.Tag.MaskGenerator: [enums.ItemType.Enumeration],
    enums.Tag.MaximumItems: [enums.ItemType.Integer],
    enums.Tag.MaximumResponseSize: [enums.ItemType.Integer],
    enums.Tag.MediaIdentifier: [enums.ItemType.TextString],
    enums.Tag.MessageExtension: [enums.ItemType.Structure],
    enums.Tag.Minor: [enums.ItemType.Integer],
    enums.Tag.Minute: [enums.ItemType.TextString],
    enums.Tag.Modulus: [enums.ItemType.BigInteger],
    enums.Tag.MonitorState: [enums.ItemType.Enumeration],
    enums.Tag.Month: [enums.ItemType.TextString],
    enums.Tag.Name: [enums.ItemType.Structure],
    enums.Tag.NameType: [enums.ItemType.Enumeration],
    enums.Tag.NameValue: [enums.ItemType.TextString],
    enums.Tag.NetworkIdentifier: [enums.ItemType.TextString],
    enums.Tag.NeverExtractable: [enums.ItemType.Boolean],
    enums.Tag.NewPassword: [enums.ItemType.TextString],
    enums.Tag.NonStop: [enums.ItemType.Boolean],
    enums.Tag.Nonce: [enums.ItemType.Structure],
    enums.Tag.NonceID: [enums.ItemType.ByteString],
    enums.Tag.NonceValue: [enums.ItemType.ByteString],
    enums.Tag.ObjectGroup: [enums.ItemType.TextString],
    enums.Tag.ObjectGroupMember: [enums.ItemType.Enumeration],
    enums.Tag.ObjectType: [enums.ItemType.Enumeration],
    enums.Tag.Offset: [enums.ItemType.Interval],
    enums.Tag.OffsetItems: [enums.ItemType.Integer],
    enums.Tag.OldPassword: [enums.ItemType.TextString],
    enums.Tag.OpaqueDataValue: [enums.ItemType.ByteString],
    enums.Tag.OpaqueObject: [enums.ItemType.Structure],
    enums.Tag.Operation: [enums.ItemType.Enumeration],
    enums.Tag.OperationPolicyName: [enums.ItemType.TextString],
    enums.Tag.OriginalCreationDate: [enums.ItemType.DateTime],
    enums.Tag.P: [enums.ItemType.BigInteger],
    enums.Tag.PGPKey: [enums.ItemType.Structure],
    enums.Tag.PGPKeyVersion: [enums.ItemType.Integer],
    enums.Tag.PIN: [enums.ItemType.TextString],
    enums.Tag.PKCS_12FriendlyName: [enums.ItemType.TextString],
    enums.Tag.PSource: [enums.ItemType.ByteString],
    enums.Tag.PaddingMethod: [enums.ItemType.Enumeration],
    enums.Tag.Password: [enums.ItemType.TextString],
    enums.Tag.Patch: [enums.ItemType.Integer],
    enums.Tag.PermissionMask: [enums.ItemType.Integer],
    enums.Tag.PortRangeEnd: [enums.ItemType.Integer],
    enums.Tag.PortRangeStart: [enums.ItemType.Integer],
    enums.Tag.PredictionResistance: [enums.ItemType.Boolean],
    enums.Tag.PrimeExponentP: [enums.ItemType.BigInteger],
    enums.Tag.PrimeExponentQ: [enums.ItemType.BigInteger],
    enums.Tag.PrimeFieldSize: [enums.ItemType.BigInteger],
    enums.Tag.PrivateExponent: [enums.ItemType.BigInteger],
    enums.Tag.PrivateKey: [enums.ItemType.Structure],
    enums.Tag.PrivateKeyTemplateAttribute: [enums.ItemType.Structure],
    enums.Tag.PrivateKeyUniqueIdentifier: [enums.ItemType.TextString],
    enums.Tag.ProcessStartDate: [enums.ItemType.DateTime],
    enums.Tag.ProfileInformation: [enums.ItemType.Structure],
    enums.Tag.ProfileName: [enums.ItemType.Enumeration],
    enums.Tag.ProtectStopDate: [enums.ItemType.DateTime],
    enums.Tag.ProtocolVersion: [enums.ItemType.Structure],
    enums.Tag.ProtocolVersionMajor: [enums.ItemType.Integer],
    enums.Tag.ProtocolVersionMinor: [enums.ItemType.Integer],
    enums.Tag.PublicExponent: [enums.ItemType.BigInteger],
    enums.Tag.PublicKey: [enums.ItemType.Structure],
    enums.Tag.PublicKeyTemplateAttribute: [enums.ItemType.Structure],
    enums.Tag.PublicKeyUniqueIdentifier: [enums.ItemType.TextString],
    enums.Tag.PutFunction: [enums.ItemType.Enumeration],
    enums.Tag.Q: [enums.ItemType.BigInteger],
    enums.Tag.QString: [enums.ItemType.ByteString],
    enums.Tag.Qlength: [enums.ItemType.Integer],
    enums.Tag.QueryFunction: [enums.ItemType.Enumeration],
    enums.Tag.RAM: [enums.ItemType.Integer],
    enums.Tag.RNGAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.RNGMode: [enums.ItemType.Enumeration],
    enums.Tag.RNGParameters: [enums.ItemType.Structure],
    enums.Tag.RandomIV: [enums.ItemType.Boolean],
    enums.Tag.RandomNumberGenerator: [enums.ItemType.Structure],
    enums.Tag.RecommendedCurve: [enums.ItemType.Enumeration],
    enums.Tag.RelativePath: [enums.ItemType.TextString],
    enums.Tag.RemoveVHSMPortRange: [enums.ItemType.Boolean],
    enums.Tag.ReplacedUniqueIdentifier: [enums.ItemType.TextString],
    enums.Tag.RequestHeader: [enums.ItemType.Structure],
    enums.Tag.RequestMessage: [enums.ItemType.Structure],
    enums.Tag.RequestPayload: [enums.ItemType.Structure],
    enums.Tag.ResponseHeader: [enums.ItemType.Structure],
    enums.Tag.ResponseMessage: [enums.ItemType.Structure],
    enums.Tag.ResponsePayload: [enums.ItemType.Structure],
    enums.Tag.Restart: [enums.ItemType.Boolean],
    enums.Tag.ResultMessage: [enums.ItemType.TextString],
    enums.Tag.ResultReason: [enums.ItemType.Enumeration],
    enums.Tag.ResultStatus: [enums.ItemType.Enumeration],
    enums.Tag.RevocationMessage: [enums.ItemType.TextString],
    enums.Tag.RevocationReason: [enums.ItemType.Structure],
    enums.Tag.RevocationReasonCode: [enums.ItemType.Enumeration],
    enums.Tag.SEApplicationData: [enums.ItemType.Structure],
    enums.Tag.SEApplicationInstanceUsage: [enums.ItemType.Structure],
    enums.Tag.SEApplicationState: [enums.ItemType.Enumeration],
    enums.Tag.SEApplicationUsage: [enums.ItemType.Structure],
    enums.Tag.SELanguage: [enums.ItemType.Enumeration],
    enums.Tag.SELogRequest: [enums.ItemType.Structure],
    enums.Tag.SELogResponse: [enums.ItemType.Structure],
    enums.Tag.Salt: [enums.ItemType.ByteString],
    enums.Tag.SaltLength: [enums.ItemType.Integer],
    enums.Tag.Second: [enums.ItemType.TextString],
    enums.Tag.SecretData: [enums.ItemType.Structure],
    enums.Tag.SecretDataType: [enums.ItemType.Enumeration],
    enums.Tag.Sensitive: [enums.ItemType.Boolean],
    enums.Tag.SerialNumber: [enums.ItemType.TextString],
    enums.Tag.ServerCertificate: [enums.ItemType.ByteString],
    enums.Tag.ServerCorrelationValue: [enums.ItemType.TextString],
    enums.Tag.ServerInformation: [enums.ItemType.Structure],
    enums.Tag.ServerPort: [enums.ItemType.Integer],
    enums.Tag.ServerURI: [enums.ItemType.TextString],
    enums.Tag.ShreddingAlgorithm: [enums.ItemType.Enumeration],
    enums.Tag.SignatureData: [enums.ItemType.ByteString],
    enums.Tag.SourceDir: [enums.ItemType.Enumeration],
    enums.Tag.SplitKey: [enums.ItemType.Structure],
    enums.Tag.SplitKeyMethod: [enums.ItemType.Enumeration],
    enums.Tag.SplitKeyParts: [enums.ItemType.Integer],
    enums.Tag.SplitKeyThreshold: [enums.ItemType.Integer],
    enums.Tag.StartNow: [enums.ItemType.Boolean],
    enums.Tag.StartOnBoot: [enums.ItemType.Boolean],
    enums.Tag.State: [enums.ItemType.Enumeration],
    enums.Tag.StorageStatusMask: [enums.ItemType.Integer],
    enums.Tag.StreamingCapability: [enums.ItemType.Boolean],
    enums.Tag.SubjectAlternativeName: [enums.ItemType.ByteString],
    enums.Tag.SubjectDistinguishedName: [enums.ItemType.ByteString],
    enums.Tag.SymmetricKey: [enums.ItemType.Structure],
    enums.Tag.SystemContact: [enums.ItemType.TextString],
    enums.Tag.SystemDescription: [enums.ItemType.TextString],
    enums.Tag.SystemLocation: [enums.ItemType.TextString],
    enums.Tag.SystemName: [enums.ItemType.TextString],
    enums.Tag.SystemServices: [enums.ItemType.Integer],
    enums.Tag.TTLVPort: [enums.ItemType.Integer],
    enums.Tag.TagLength: [enums.ItemType.Integer],
    enums.Tag.Temperature: [enums.ItemType.Integer],
    enums.Tag.Template: [enums.ItemType.Structure],
    enums.Tag.TemplateAttribute: [enums.ItemType.Structure],
    enums.Tag.TimeStamp: [enums.ItemType.DateTime],
    enums.Tag.Timezone: [enums.ItemType.TextString],
    enums.Tag.UniqueBatchItemID: [enums.ItemType.ByteString],
    enums.Tag.UniqueIdentifier: [enums.ItemType.TextString],
    enums.Tag.UnwrapMode: [enums.ItemType.Enumeration],
    enums.Tag.Usage: [enums.ItemType.Structure],
    enums.Tag.UsageLimits: [enums.ItemType.Structure],
    enums.Tag.UsageLimitsCount: [enums.ItemType.LongInteger],
    enums.Tag.UsageLimitsTotal: [enums.ItemType.LongInteger],
    enums.Tag.UsageLimitsUnit: [enums.ItemType.Enumeration],
    enums.Tag.UserCertificate: [enums.ItemType.ByteString],
    enums.Tag.UserCertificateRequest: [enums.ItemType.ByteString],
    enums.Tag.UserInformation: [enums.ItemType.Structure],
    enums.Tag.UserName: [enums.ItemType.TextString],
    enums.Tag.UserType: [enums.ItemType.Enumeration],
    enums.Tag.Username: [enums.ItemType.TextString],
    enums.Tag.VCOName: [enums.ItemType.TextString],
    enums.Tag.VCOPin: [enums.ItemType.TextString],
    enums.Tag.VHSMName: [enums.ItemType.TextString],
    enums.Tag.VHSMOptions: [enums.ItemType.Structure],
    enums.Tag.VHSMUniqueID: [enums.ItemType.Integer],
    enums.Tag.VHSMUsage: [enums.ItemType.Structure],
    enums.Tag.ValidationAuthorityCountry: [enums.ItemType.TextString],
    enums.Tag.ValidationAuthorityType: [enums.ItemType.Enumeration],
    enums.Tag.ValidationAuthorityURI: [enums.ItemType.TextString],
    enums.Tag.ValidationCertificateIdentifier: [enums.ItemType.TextString],
    enums.Tag.ValidationCertificateURI: [enums.ItemType.TextString],
    enums.Tag.ValidationInformation: [enums.ItemType.Structure],
    enums.Tag.ValidationLevel: [enums.ItemType.Integer],
    enums.Tag.ValidationProfile: [enums.ItemType.TextString],
    enums.Tag.ValidationType: [enums.ItemType.Enumeration],
    enums.Tag.ValidationVendorURI: [enums.ItemType.TextString],
    enums.Tag.ValidationVersionMajor: [enums.ItemType.Integer],
    enums.Tag.ValidationVersionMinor: [enums.ItemType.Integer],
    enums.Tag.ValidityDate: [enums.ItemType.DateTime],
    enums.Tag.ValidityIndicator: [enums.ItemType.Enumeration],
    enums.Tag.VendorExtension: [enums.ItemType.Structure],
    enums.Tag.VendorIdentification: [enums.ItemType.TextString],
    enums.Tag.Version: [enums.ItemType.Structure],
    enums.Tag.VirtualHSMData: [enums.ItemType.Structure],
    enums.Tag.WrappingMethod: [enums.ItemType.Enumeration],
    enums.Tag.X: [enums.ItemType.BigInteger],
    enums.Tag.X_509CertificateIdentifier: [enums.ItemType.Structure],
    enums.Tag.X_509CertificateIssuer: [enums.ItemType.Structure],
    enums.Tag.X_509CertificateSubject: [enums.ItemType.Structure],
    enums.Tag.Y: [enums.ItemType.BigInteger],
    enums.Tag.Year: [enums.ItemType.TextString],
}

ATTRIBUTE_TAG_NAME_MAP = {
    enums.Tag.UniqueIdentifier: "Unique Identifier",
    enums.Tag.Name: "Name",
    enums.Tag.ObjectType: "Object Type",
    enums.Tag.CryptographicAlgorithm: "Cryptographic Algorithm",
    enums.Tag.CryptographicLength: "Cryptographic Length",
    enums.Tag.CryptographicParameters: "Cryptographic Parameters",
    enums.Tag.CryptographicDomainParameters: "Cryptographic Domain Parameters",
    enums.Tag.CertificateType: "Certificate Type",
    enums.Tag.CertificateLength: "Certificate Length",
    enums.Tag.X_509CertificateIdentifier: "X.509 Certificate Identifier",
    enums.Tag.X_509CertificateSubject: "X.509 Certificate Subject",
    enums.Tag.X_509CertificateIssuer: "X.509 Certificate Issuer",
    enums.Tag.CertificateIdentifier: "Certificate Identifier",
    enums.Tag.CertificateSubject: "Certificate Subject",
    enums.Tag.CertificateIssuer: "Certificate Issuer",
    enums.Tag.DigitalSignatureAlgorithm: "Digital Signature Algorithm",
    enums.Tag.Digest: "Digest",
    enums.Tag.OperationPolicyName: "Operation Policy Name",
    enums.Tag.CryptographicUsageMask: "Cryptographic Usage Mask",
    enums.Tag.LeaseTime: "Lease Time",
    enums.Tag.UsageLimits: "Usage Limits",
    enums.Tag.State: "State",
    enums.Tag.InitialDate: "Initial Date",
    enums.Tag.ActivationDate: "Activation Date",
    enums.Tag.ProcessStartDate: "Process Start Date",
    enums.Tag.ProtectStopDate: "Protect Stop Date",
    enums.Tag.DeactivationDate: "Deactivation Date",
    enums.Tag.DestroyDate: "Destroy Date",
    enums.Tag.CompromiseOccurrenceDate: "Compromise Occurrence Date",
    enums.Tag.CompromiseDate: "Compromise Date",
    enums.Tag.RevocationReason: "Revocation Reason",
    enums.Tag.ArchiveDate: "Archive Date",
    enums.Tag.ObjectGroup: "Object Group",
    enums.Tag.Fresh: "Fresh",
    enums.Tag.Link: "Link",
    enums.Tag.ApplicationSpecificInformation: "Application Specific Information",
    enums.Tag.ContactInformation: "Contact Information",
    enums.Tag.LastChangeDate: "Last Change Date",
    enums.Tag.CustomAttribute: "Custom Attribute",
    enums.Tag.AlternativeName: "Alternative Name",
    enums.Tag.KeyValuePresent: "Key Value Present",
    enums.Tag.KeyValueLocation: "Key Value Location",
    enums.Tag.OriginalCreationDate: "Original Creation Date",
    enums.Tag.RandomNumberGenerator: "Random Number Generator",
    enums.Tag.Sensitive: "Sensitive",
    enums.Tag.AlwaysSensitive: "Always Sensitive",
    enums.Tag.Extractable: "Extractable",
    enums.Tag.NeverExtractable: "Never Extractable",
}
